version: "3"

services:
  traefik:
    image: traefik:v2.0
    restart: always
    ports:
      - 8123:8123
      - 443:443
    command:
      - "--global.sendAnonymousUsage=false"
      - "--providers.docker"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.autls.address=:8123"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/acme/acme.json"
      - "--api.dashboard=true"
      - "--providers.docker.exposedbydefault=false"
    volumes:
      -  /var/run/docker.sock:/var/run/docker.sock        
      - ./acme/:/etc/acme/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.rule=Host(`${DOMAIN_NAME}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${AUTH_STRING}"
#    logging:
#      driver: json-file

  amongusdiscord:
#    build:https://github.com/denverquane/amongusdiscord.git
    build: https://github.com/RichUncleCody/amongusdiscord.git
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
#   logging:
#     driver: json-file

  amongusbroker:
    build: .
    environment:
      - BACKEND_SERVER=amongusdiscord
      - DB=redis
    depends_on:
      - amongusdiscord
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.services.autls.loadbalancer.server.port=8123"
      - "traefik.tcp.routers.autls.entrypoints=autls"
      - "traefik.tcp.routers.autls.rule=HostSNI(`${DOMAIN_NAME}`)"
      - "traefik.tcp.routers.autls.service=autls"
      - "traefik.tcp.routers.autls.tls.certresolver=letsencrypt"
#    logging:
#      driver: json-file

  redis:
    image: "redis:latest"
    command: redis-server
#    logging:
#      driver: json-file
